### ISSUE TITLE
Should we support push (and splice)?

### ISSUE THREAD

**Issue by davegraham92120** [geistinteractive/fm-json-additions#13]
FileMaker's JSONSetElement function will only insert an object into an array at a specific index. What I really need is a way to push an object at the end of an array and I don't see that being possible with the native functions.

With JSON.ArrayLength it's pretty simple, but I think a CF makes sense (see below). I haven't written any tests yet. I wanted to make sure that we think this (and possibly splice as well) would be valuable before spending time on it.

/**
 * =====================================
 * JSON.ArrayPush ( theArray ; theObject )
 *
 * RETURNS:
 *	The array with the object inserted at the end
 *
 * PARAMETERS:
 *	theArray 
 *	theObject 
 *
 * DEPENDENCIES:
 *	JSON.ArrayLength custom function
 *	FileMaker 16 or Later
 *
 * NOTES:
 *
 *
 * FAMILY:
 *	JSON - Extensions to the Native JSON Functions
 * 
 * HISTORY:
 *	Created, 2017-07-20, dave@geistinteractive.com
 *
 * =====================================
 */

Let ( [ 
	// Since JSON arrays are zero-based, the size of the array
	// will be the index that we are going to insert the object
	insertAtIndex = JSON.ArrayLength ( theArray ; "" ) 
] ; 
	// Insert the object at the end of the array
	JSONSetElement ( theArray ; insertAtIndex ; theObject ; JSONObject )
)

**Comment by davegraham92120** [comment]
I added JSON.Push and also fixed some errors in the doc block for JSON.IsValid

See attached with tests.

[JSONAdditions with Push.fmp12.zip](https://github.com/geistinteractive/fm-json-additions/files/1516940/JSONAdditions.with.Push.fmp12.zip)

**Comment by toddgeist** [comment]
Why does this throw an error?

 `JSON.Push ( "[]" ; "foo bar" ) ` 

why not this?

```
JSON.Push ( Test::JSON ; "foo bar" ) 
//=> ["foo bar"]
```

`["foo bar"]` is a perfectly valid array

**Comment by davegraham92120** [comment]
Good point. I've updated the function to validate the target instead of the source. If there's an error with the source, the JSONSetElement function will return a standard error. I also included a lot more tests, including one that fails.

[JSONAdditions with Push.fmp12.zip](https://github.com/geistinteractive/fm-json-additions/files/1519099/JSONAdditions.with.Push.fmp12.zip)

**Comment by toddgeist** [comment]
4 tests with this file fail.  Maybe you attached the wrong file?

**Comment by davegraham92120** [comment]
Crap. I accidentally changed a couple things after I had tested, and forgot to re-test. Here you go...

[JSONAdditions with Push.fmp12.zip](https://github.com/geistinteractive/fm-json-additions/files/1522034/JSONAdditions.with.Push.fmp12.zip)

**Comment by toddgeist** [comment]
:-) . This is EXACTLY why you do things this way.

**Comment by davegraham92120** [comment]
I’ll learn eventually (maybe). ;-)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mw777rcc** [comment]
Yeah that wasn't an accusation by Todd, it was praise for test driven
devlopment. :-)

Best regards,

Michael A. Wallace, Sr.
Senior Engineer
Richard Carlton Consulting Inc.
Office (707) 567-3189 (Primary)
Corp   (408) 492-9701
Fax    (707) 422-4903
michael.wallace@rcconsulting.com
www.rcconsulting.com

**Comment by davegraham92120** [comment]
I get it...just being difficult. ;-)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tjsoftworks** [comment]
Nice work .... this TDD conversation!
