### ISSUE TITLE
JSON.ContainsProperty only handles single level

### ISSUE THREAD

**Issue by rwu2359** [geistinteractive/fm-json-additions#3]
JSON.ContainsProperty will not see key when path is
```
JSON.ContainsProperty ( Test::JSON ; "post.body" )
or
JSON.ContainsProperty ( Test::JSON ; "post.body.item" )
```
amended file and tests attached

[JSONAdditions.fmp12.zip](https://github.com/geistinteractive/fm-json-additions/files/1005036/JSONAdditions.fmp12.zip)

**Comment by toddgeist** [comment]
Thanks so much for taking the time to do this.  I'd love to include this.  However as written it breaks three tests.  Any chance you can fix that?
![failing tests](https://cloud.githubusercontent.com/assets/316792/26117054/1a289f22-3a1a-11e7-9f12-fc16d1709f79.gif)

**Comment by rwu2359** [comment]
That's wierd as I only submitted after passing tests at this end...

<img width="1303" alt="screen shot 2017-05-16 at 18 12 28" src="https://cloud.githubusercontent.com/assets/779522/26118882/58afb296-3a63-11e7-9ce9-764f96ed8002.png">

I deleted the zip and then re-uploaded it, maybe that gave you the older one..
Try this.

[JSONAdditions.fmp12.zip](https://github.com/geistinteractive/fm-json-additions/files/1005275/JSONAdditions.fmp12.zip)

**Comment by toddgeist** [comment]
Well this explains it
![image](https://cloud.githubusercontent.com/assets/316792/26119534/5f17a65c-3a22-11e7-9dfd-ba3aab8eb9dc.png)

**Comment by toddgeist** [comment]
I was running the Damn thing in FileMaker 15

UHGGHHHBHH

any how this looks good we'll get it in place
