### ISSUE TITLE
ArrayGetValuesFromPath fails if path value is "" not (null)

### ISSUE THREAD

**Issue by rwu2359** [geistinteractive/fm-json-additions#5]
if the JSON has 
```
{"key":""}
``` 
and not 
```
{"key":null}
``` 
the function will fail

amended in this version of the file, several new tests included  -which also demonstrate path depth
[JSONAdditions.fmp12.zip](https://github.com/geistinteractive/fm-json-additions/files/1005432/JSONAdditions.fmp12.zip)

**Comment by toddgeist** [comment]
excellent
